-- =====================================================
-- Security tables for JWT authentication
-- Project: Alediesme
-- Run connected as ALEDIESME (or user with DDL privileges)
-- =====================================================

-- =====================================================
-- SEQUENCE
-- =====================================================
CREATE SEQUENCE ALEDIESME.SEQ_APP_ROLE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_APP_USER START WITH 1 INCREMENT BY 1;

-- =====================================================
-- Security tables
-- Run connected as ALEDIESME (or user with DDL privileges)
-- =====================================================

-- =====================================================
-- 1. TABLE: app_role
-- =====================================================
CREATE TABLE ALEDIESME.app_role (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR2(50)  NOT NULL,
    enabled     NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at  DATE          DEFAULT SYSDATE NOT NULL,
    updated_at  DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_app_role_name UNIQUE (role_name),
    CONSTRAINT ck_app_role_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 2. TABLE: app_user
-- =====================================================
CREATE TABLE ALEDIESME.app_user (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(100) NOT NULL,
    password_hash  VARCHAR2(100) NOT NULL,
    enabled        NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at     DATE          DEFAULT SYSDATE NOT NULL,
    updated_at     DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT ck_app_user_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 3. TABLE: app_user_role
-- =====================================================
CREATE TABLE ALEDIESME.app_user_role (
    user_id    NUMBER NOT NULL,
    role_id    NUMBER NOT NULL,
    created_at DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_app_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_app_user_role_user FOREIGN KEY (user_id) REFERENCES ALEDIESME.app_user (id),
    CONSTRAINT fk_app_user_role_role FOREIGN KEY (role_id) REFERENCES ALEDIESME.app_role (id)
);

-- =================================================================================
-- Triggers to auto-populate ID columns using sequences for the app_role table
-- =================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_APP_ROLE
BEFORE INSERT ON ALEDIESME.app_role
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT ALEDIESME.SEQ_APP_ROLE.NEXTVAL INTO :NEW.id FROM dual;
    END IF;
END;
/

-- =================================================================================
-- Triggers to auto-populate ID columns using sequences for the app_user table
-- =================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_APP_USER
BEFORE INSERT ON ALEDIESME.app_user
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT ALEDIESME.SEQ_APP_USER.NEXTVAL INTO :NEW.id FROM dual;
    END IF;
END;
/

-- =====================================================
-- INSERT DEFAULT VALUES FOR app_role
-- =====================================================
INSERT INTO ALEDIESME.app_role (role_name, enabled)
VALUES ('ROLE_USER', 1);

INSERT INTO ALEDIESME.app_role (role_name, enabled)
VALUES ('ROLE_ADMIN', 1);

INSERT INTO ALEDIESME.app_role (role_name, enabled)
VALUES ('ROLE_USER_WEB', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR app_user
-- =====================================================
-- User: admin / password: admin123
-- BCrypt hash (strength 10). Generate with BcryptPasswordHasher or BcryptPasswordHasherTest
INSERT INTO ALEDIESME.app_user (username, password_hash, enabled)
VALUES (
    'admin',
    '$2a$10$PwGlkGU/CcfLzCB3C8ojxentSX6Js0wzLOXfZ.Wu0gDKIRrgrzWp.',
    1
);
INSERT INTO ALEDIESME.app_user (username, password_hash, enabled)
VALUES (
           'userWeb',
           '$2a$10$SLLLKVF1qWJewvsvDjmeFuW0vSuSAY7ONq6gfTVxnTxg1KspGOlLq',
           1
       );

-- =====================================================
-- INSERT DEFAULT VALUES FOR app_user_role
-- =====================================================
INSERT INTO ALEDIESME.app_user_role (user_id, role_id)
SELECT u.id, r.id
FROM ALEDIESME.app_user u
JOIN ALEDIESME.app_role r ON r.role_name = 'ROLE_ADMIN'
WHERE u.username = 'admin';

INSERT INTO ALEDIESME.app_user_role (user_id, role_id)
SELECT u.id, r.id
FROM ALEDIESME.app_user u
         JOIN ALEDIESME.app_role r ON r.role_name = 'ROLE_USER_WEB'
WHERE u.username = 'userWeb';

-- ================================================================================
-- Indexes
-- ================================================================================
CREATE INDEX idx_app_user_role_user ON ALEDIESME.app_user_role (user_id);
CREATE INDEX idx_app_user_role_role ON ALEDIESME.app_user_role (role_id);

-- ===============================================================================================
-- Table comments
-- ===============================================================================================
COMMENT ON TABLE ALEDIESME.app_role IS 'Application roles for JWT authorization';
COMMENT ON TABLE ALEDIESME.app_user IS 'Application users with BCrypt passwords';
COMMENT ON TABLE ALEDIESME.app_user_role IS 'Many-to-many relationship between users and roles';
COMMENT ON COLUMN ALEDIESME.app_user.password_hash IS 'BCrypt hash. Generate with BcryptPasswordHasher or BcryptPasswordHasherTest';

-- =====================================================
-- Link customer (create_data_base.sql) to app_user for web accounts
-- Requires customer table from create_data_base.sql
-- =====================================================
ALTER TABLE ALEDIESME.customer
    ADD CONSTRAINT fk_customer_app_user
    FOREIGN KEY (app_user_id) REFERENCES ALEDIESME.app_user (id);

COMMIT;
