-- =====================================================
-- Tablas de negocio usadas por la API REST actual
-- Ejecutar conectado como ALEDIESME (despues de crear el usuario)
-- =====================================================