-- =====================================================
-- Oracle database bootstrap script
-- Project: Alediesme
-- Run connected as SYS (or DBA) on the target PDB
-- =====================================================
--Checking my current situation is only useful for XE.
SHOW CON_NAME;

-- Adjust PDB name if required
ALTER SESSION SET CONTAINER = XEPDB1;

-- Dedicated profile for application accounts (no password expiration)
CREATE PROFILE APP_SERVICE_PROFILE LIMIT
    PASSWORD_LIFE_TIME UNLIMITED
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 1;

-- Change the password before running it in any environment other than the local one.
CREATE USER ALEDIESME
    IDENTIFIED BY "Cope*300823*"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS
    PROFILE APP_SERVICE_PROFILE;

-- Minimum privileges for the application to connect and perform DDL/DML operations
GRANT CONNECT, RESOURCE TO ALEDIESME;
GRANT CREATE SESSION TO ALEDIESME;
GRANT CREATE TABLE TO ALEDIESME;
GRANT CREATE VIEW TO ALEDIESME;
GRANT CREATE SEQUENCE TO ALEDIESME;
GRANT CREATE PROCEDURE TO ALEDIESME;
GRANT CREATE TRIGGER TO ALEDIESME;

-- =====================================================
-- SEQUENCE
-- =====================================================
CREATE SEQUENCE ALEDIESME.SEQ_DOCUMENT_TYPE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_COUNTRY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_STATE_PROVINCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_CITY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_NEIGHBORHOOD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_GENDER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_MARITAL_STATUS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_USER_TYPE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_CURRENCY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_ORDER_STATUS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_PAYMENT_METHOD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALEDIESME.SEQ_CUSTOMER START WITH 1 INCREMENT BY 1;

-- =====================================================
-- Reference catalog tables
-- Run connected as ALEDIESME (or user with DDL privileges)si uestoy
-- =====================================================
-- =====================================================
-- 1. TABLE: document_type
-- =====================================================
CREATE TABLE ALEDIESME.document_type (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR2(10)  NOT NULL,
    name         VARCHAR2(100) NOT NULL,
    abbreviation VARCHAR2(5),
    enabled      NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at   DATE          DEFAULT SYSDATE NOT NULL,
    updated_at   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_document_type_code UNIQUE (code),
    CONSTRAINT ck_document_type_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 2. TABLE: country
-- =====================================================
CREATE TABLE ALEDIESME.country (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_code   VARCHAR2(2)   NOT NULL,
    name       VARCHAR2(100) NOT NULL,
    demonym    VARCHAR2(50),
    enabled    NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at DATE          DEFAULT SYSDATE NOT NULL,
    updated_at DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_country_iso_code UNIQUE (iso_code),
    CONSTRAINT uk_country_name UNIQUE (name),
    CONSTRAINT ck_country_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 3. TABLE: state_province
-- =====================================================
CREATE TABLE ALEDIESME.state_province (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id NUMBER        NOT NULL,
    code       VARCHAR2(5)   NOT NULL,
    name       VARCHAR2(100) NOT NULL,
    enabled    NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at DATE          DEFAULT SYSDATE NOT NULL,
    updated_at DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_state_province_country FOREIGN KEY (country_id) REFERENCES ALEDIESME.country (id),
    CONSTRAINT uk_state_province_country_code UNIQUE (country_id, code),
    CONSTRAINT ck_state_province_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 4. TABLE: city
-- =====================================================
CREATE TABLE ALEDIESME.city (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_province_id NUMBER        NOT NULL,
    code              VARCHAR2(5)   NOT NULL,
    name              VARCHAR2(100) NOT NULL,
    enabled           NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at        DATE          DEFAULT SYSDATE NOT NULL,
    updated_at        DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_city_state_province FOREIGN KEY (state_province_id) REFERENCES ALEDIESME.state_province (id),
    CONSTRAINT uk_city_state_province_code UNIQUE (state_province_id, code),
    CONSTRAINT ck_city_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 5. TABLE: neighborhood
-- =====================================================
CREATE TABLE ALEDIESME.neighborhood (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id    NUMBER        NOT NULL,
    code       VARCHAR2(10),
    name       VARCHAR2(100) NOT NULL,
    enabled    NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at DATE          DEFAULT SYSDATE NOT NULL,
    updated_at DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_neighborhood_city FOREIGN KEY (city_id) REFERENCES ALEDIESME.city (id),
    CONSTRAINT ck_neighborhood_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 6. TABLE: gender
-- =====================================================
CREATE TABLE ALEDIESME.gender (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR2(1)  NOT NULL,
    name       VARCHAR2(50) NOT NULL,
    enabled    NUMBER(1)    DEFAULT 1 NOT NULL,
    created_at DATE         DEFAULT SYSDATE NOT NULL,
    updated_at DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_gender_code UNIQUE (code),
    CONSTRAINT uk_gender_name UNIQUE (name),
    CONSTRAINT ck_gender_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 7. TABLE: marital_status
-- =====================================================
CREATE TABLE ALEDIESME.marital_status (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR2(2)  NOT NULL,
    name       VARCHAR2(50) NOT NULL,
    enabled    NUMBER(1)    DEFAULT 1 NOT NULL,
    created_at DATE         DEFAULT SYSDATE NOT NULL,
    updated_at DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_marital_status_code UNIQUE (code),
    CONSTRAINT uk_marital_status_name UNIQUE (name),
    CONSTRAINT ck_marital_status_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 8. TABLE: user_type
-- =====================================================
CREATE TABLE ALEDIESME.user_type (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR2(10)  NOT NULL,
    name        VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    enabled     NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at  DATE          DEFAULT SYSDATE NOT NULL,
    updated_at  DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_user_type_code UNIQUE (code),
    CONSTRAINT uk_user_type_name UNIQUE (name),
    CONSTRAINT ck_user_type_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 9. TABLE: currency
-- =====================================================
CREATE TABLE ALEDIESME.currency (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR2(3)  NOT NULL,
    name       VARCHAR2(50) NOT NULL,
    symbol     VARCHAR2(5),
    enabled    NUMBER(1)    DEFAULT 1 NOT NULL,
    created_at DATE         DEFAULT SYSDATE NOT NULL,
    updated_at DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_currency_code UNIQUE (code),
    CONSTRAINT uk_currency_name UNIQUE (name),
    CONSTRAINT ck_currency_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 10. TABLE: order_status
-- =====================================================
CREATE TABLE ALEDIESME.order_status (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR2(10) NOT NULL,
    name           VARCHAR2(50) NOT NULL,
    description    VARCHAR2(500),
    display_order  NUMBER,
    enabled        NUMBER(1)    DEFAULT 1 NOT NULL,
    created_at     DATE         DEFAULT SYSDATE NOT NULL,
    updated_at     DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_order_status_code UNIQUE (code),
    CONSTRAINT uk_order_status_name UNIQUE (name),
    CONSTRAINT ck_order_status_enabled CHECK (enabled IN (0, 1))
);

-- =====================================================
-- 11. TABLE: payment_method
-- =====================================================
CREATE TABLE ALEDIESME.payment_method (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR2(10) NOT NULL,
    name                 VARCHAR2(50) NOT NULL,
    description          VARCHAR2(500),
    requires_validation  NUMBER(1)    DEFAULT 1 NOT NULL,
    enabled              NUMBER(1)    DEFAULT 1 NOT NULL,
    created_at           DATE         DEFAULT SYSDATE NOT NULL,
    updated_at           DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_payment_method_code UNIQUE (code),
    CONSTRAINT uk_payment_method_name UNIQUE (name),
    CONSTRAINT ck_payment_method_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_payment_method_requires_validation CHECK (requires_validation IN (0, 1))
);

-- =====================================================
-- 12. TABLE: customer
-- Business customers for the jewelry store (separate from app_user login)
-- app_user_id FK is added in app_security_users.sql (after app_user exists)
-- =====================================================
CREATE TABLE ALEDIESME.customer (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id           NUMBER,
    user_type_id          NUMBER        NOT NULL,
    document_type_id      NUMBER        NOT NULL,
    document_number       VARCHAR2(30)  NOT NULL,
    first_name            VARCHAR2(100) NOT NULL,
    last_name             VARCHAR2(100) NOT NULL,
    email                 VARCHAR2(150),
    phone                 VARCHAR2(30),
    mobile_phone          VARCHAR2(30),
    gender_id             NUMBER,
    marital_status_id     NUMBER,
    birth_date            DATE,
    anniversary_date      DATE,
    neighborhood_id       NUMBER,
    address_line          VARCHAR2(200),
    address_complement    VARCHAR2(100),
    postal_code           VARCHAR2(20),
    preferred_currency_id NUMBER,
    accepts_marketing     NUMBER(1)     DEFAULT 0 NOT NULL,
    notes                 VARCHAR2(500),
    enabled               NUMBER(1)     DEFAULT 1 NOT NULL,
    created_at            DATE          DEFAULT SYSDATE NOT NULL,
    updated_at            DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_customer_user_type FOREIGN KEY (user_type_id)
        REFERENCES ALEDIESME.user_type (id),
    CONSTRAINT fk_customer_document_type FOREIGN KEY (document_type_id)
        REFERENCES ALEDIESME.document_type (id),
    CONSTRAINT fk_customer_gender FOREIGN KEY (gender_id)
        REFERENCES ALEDIESME.gender (id),
    CONSTRAINT fk_customer_marital_status FOREIGN KEY (marital_status_id)
        REFERENCES ALEDIESME.marital_status (id),
    CONSTRAINT fk_customer_neighborhood FOREIGN KEY (neighborhood_id)
        REFERENCES ALEDIESME.neighborhood (id),
    CONSTRAINT fk_customer_preferred_currency FOREIGN KEY (preferred_currency_id)
        REFERENCES ALEDIESME.currency (id),
    CONSTRAINT uk_customer_document UNIQUE (document_type_id, document_number),
    CONSTRAINT uk_customer_app_user UNIQUE (app_user_id),
    CONSTRAINT uk_customer_email UNIQUE (email),
    CONSTRAINT ck_customer_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_customer_accepts_marketing CHECK (accepts_marketing IN (0, 1))
);

-- =================================================================================
-- Triggers to auto-populate ID columns using sequences for the document_type table
-- =================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_DOCUMENT_TYPE
BEFORE INSERT ON ALEDIESME.document_type
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_DOCUMENT_TYPE.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ===========================================================================
-- Triggers to auto-populate ID columns using sequences for the country table
-- ===========================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_COUNTRY
BEFORE INSERT ON ALEDIESME.country
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_COUNTRY.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ==================================================================================
-- Triggers to auto-populate ID columns using sequences for the state_province table
-- ==================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_STATE_PROVINCE
BEFORE INSERT ON ALEDIESME.state_province
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_STATE_PROVINCE.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- =======================================================================
-- Triggers to auto-populate ID columns using sequences for the city table
-- =======================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_CITY
BEFORE INSERT ON ALEDIESME.city
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_CITY.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ================================================================================
-- Triggers to auto-populate ID columns using sequences for the neighborhood table
-- ================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_NEIGHBORHOOD
BEFORE INSERT ON ALEDIESME.neighborhood
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_NEIGHBORHOOD.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ==========================================================================
-- Triggers to auto-populate ID columns using sequences for the gender table
-- ==========================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_GENDER
BEFORE INSERT ON ALEDIESME.gender
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_GENDER.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ===================================================================================
-- Triggers to auto-populate ID columns using sequences for the marital_status table
-- ===================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_MARITAL_STATUS
BEFORE INSERT ON ALEDIESME.marital_status
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_MARITAL_STATUS.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- =============================================================================
-- Triggers to auto-populate ID columns using sequences for the user_type table
-- =============================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_USER_TYPE
BEFORE INSERT ON ALEDIESME.user_type
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_USER_TYPE.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- =============================================================================
-- Triggers to auto-populate ID columns using sequences for the currency table
-- =============================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_CURRENCY
BEFORE INSERT ON ALEDIESME.currency
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_CURRENCY.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ================================================================================
-- Triggers to auto-populate ID columns using sequences for the order_status table
-- ================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_ORDER_STATUS
BEFORE INSERT ON ALEDIESME.order_status
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_ORDER_STATUS.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ===================================================================================
-- Triggers to auto-populate ID columns using sequences for the payment_method table
-- ===================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_PAYMENT_METHOD
BEFORE INSERT ON ALEDIESME.payment_method
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
SELECT ALEDIESME.SEQ_PAYMENT_METHOD.NEXTVAL INTO :NEW.id FROM dual;
END IF;
END;
/
-- ===================================================================================
-- Triggers to auto-populate ID columns using sequences for the customer table
-- ===================================================================================
CREATE OR REPLACE TRIGGER ALEDIESME.TRG_CUSTOMER
BEFORE INSERT ON ALEDIESME.customer
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT ALEDIESME.SEQ_CUSTOMER.NEXTVAL INTO :NEW.id FROM dual;
    END IF;
END;
/
-- =====================================================
-- INSERT DEFAULT VALUES FOR document_type
-- =====================================================
INSERT INTO ALEDIESME.document_type (code, name, abbreviation, enabled)
VALUES ('CC', 'Citizenship ID', 'CC', 1);
INSERT INTO ALEDIESME.document_type (code, name, abbreviation, enabled)
VALUES ('CE', 'Foreign ID', 'CE', 1);
INSERT INTO ALEDIESME.document_type (code, name, abbreviation, enabled)
VALUES ('PA', 'Passport', 'PA', 1);
INSERT INTO ALEDIESME.document_type (code, name, abbreviation, enabled)
VALUES ('NIT', 'Tax Identification Number', 'NIT', 1);
INSERT INTO ALEDIESME.document_type (code, name, abbreviation, enabled)
VALUES ('TI', 'Identity Card', 'TI', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR country
-- =====================================================
INSERT INTO ALEDIESME.country (iso_code, name, demonym, enabled) VALUES ('CO', 'Colombia', 'Colombian', 1);
INSERT INTO ALEDIESME.country (iso_code, name, demonym, enabled) VALUES ('MX', 'Mexico', 'Mexican', 1);
INSERT INTO ALEDIESME.country (iso_code, name, demonym, enabled) VALUES ('AR', 'Argentina', 'Argentine', 1);
INSERT INTO ALEDIESME.country (iso_code, name, demonym, enabled) VALUES ('EC', 'Ecuador', 'Ecuadorian', 1);
INSERT INTO ALEDIESME.country (iso_code, name, demonym, enabled) VALUES ('PE', 'Peru', 'Peruvian', 1);
INSERT INTO ALEDIESME.country (iso_code, name, demonym, enabled) VALUES ('ES', 'Spain', 'Spanish', 1);
INSERT INTO ALEDIESME.country (iso_code, name, demonym, enabled) VALUES ('US', 'United States', 'American', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR state_province
-- =====================================================
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '05', 'Antioquia', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '08', 'Atlantic', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '11', 'Bogota D.C.', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '13', 'Bolivar', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '15', 'Boyaca', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '17', 'Caldas', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '18', 'Caqueta', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '19', 'Cauca', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '20', 'Cesar', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '23', 'Cordoba', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '25', 'Cundinamarca', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '27', 'Guaviare', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '41', 'Huila', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '44', 'La Guajira', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '47', 'Magdalena', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '50', 'Meta', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '52', 'Narino', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '54', 'North Santander', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '63', 'Quindio', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '66', 'Risaralda', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '68', 'Santander', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '70', 'Sucre', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '73', 'Tolima', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '76', 'Valle del Cauca', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '81', 'Arauca', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '85', 'Casanare', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '86', 'Putumayo', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '88', 'San Andres and Providencia', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '91', 'Amazonas', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '94', 'Vaupes', 1);
INSERT INTO ALEDIESME.state_province (country_id, code, name, enabled) VALUES (1, '95', 'Vichada', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR city
-- =====================================================
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (1, '05001', 'Medellin', 1);
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (1, '05002', 'Abejorral', 1);
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (1, '05004', 'Amalfi', 1);
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (1, '05021', 'Bello', 1);
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (1, '05105', 'Itagui', 1);
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (1, '05089', 'Envigado', 1);
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (3, '11001', 'Bogota', 1);
INSERT INTO ALEDIESME.city (state_province_id, code, name, enabled) VALUES (2, '08001', 'Barranquilla', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR neighborhood
-- =====================================================
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001001', 'Popular', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001002', 'Santa Cruz', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001003', 'Manrique', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001004', 'Arvi', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001005', 'Castilla', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001006', 'Doce de Octubre', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001007', 'Robledo', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001008', 'Villa Hermosa', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001009', 'Buenos Aires', 1);
INSERT INTO ALEDIESME.neighborhood (city_id, code, name, enabled) VALUES (1, '05001010', 'San Rafael', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR gender
-- =====================================================
INSERT INTO ALEDIESME.gender (code, name, enabled) VALUES ('M', 'Male', 1);
INSERT INTO ALEDIESME.gender (code, name, enabled) VALUES ('F', 'Female', 1);
INSERT INTO ALEDIESME.gender (code, name, enabled) VALUES ('O', 'Other', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR marital_status
-- =====================================================
INSERT INTO ALEDIESME.marital_status (code, name, enabled) VALUES ('S', 'Single', 1);
INSERT INTO ALEDIESME.marital_status (code, name, enabled) VALUES ('C', 'Married', 1);
INSERT INTO ALEDIESME.marital_status (code, name, enabled) VALUES ('D', 'Divorced', 1);
INSERT INTO ALEDIESME.marital_status (code, name, enabled) VALUES ('V', 'Widowed', 1);
INSERT INTO ALEDIESME.marital_status (code, name, enabled) VALUES ('U', 'Common Law', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR user_type
-- =====================================================
INSERT INTO ALEDIESME.user_type (code, name, description, enabled)
VALUES ('ADM', 'Administrator', 'User with full system access', 1);
INSERT INTO ALEDIESME.user_type (code, name, description, enabled)
VALUES ('USR', 'User', 'Standard user with limited access', 1);
INSERT INTO ALEDIESME.user_type (code, name, description, enabled)
VALUES ('VEN', 'Seller', 'User with sales permissions', 1);
INSERT INTO ALEDIESME.user_type (code, name, description, enabled)
VALUES ('CLI', 'Client', 'Customer user for purchases', 1);
INSERT INTO ALEDIESME.user_type (code, name, description, enabled)
VALUES ('MOD', 'Moderator', 'User with moderation permissions', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR currency
-- =====================================================
INSERT INTO ALEDIESME.currency (code, name, symbol, enabled) VALUES ('COP', 'Colombian Peso', '$', 1);
INSERT INTO ALEDIESME.currency (code, name, symbol, enabled) VALUES ('USD', 'US Dollar', 'USD', 1);
INSERT INTO ALEDIESME.currency (code, name, symbol, enabled) VALUES ('EUR', 'Euro', 'EUR', 1);
INSERT INTO ALEDIESME.currency (code, name, symbol, enabled) VALUES ('MXN', 'Mexican Peso', 'MXN', 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR order_status
-- =====================================================
INSERT INTO ALEDIESME.order_status (code, name, description, display_order, enabled)
VALUES ('PEN', 'Pending', 'Order pending processing', 1, 1);
INSERT INTO ALEDIESME.order_status (code, name, description, display_order, enabled)
VALUES ('CON', 'Confirmed', 'Order confirmed by the customer', 2, 1);
INSERT INTO ALEDIESME.order_status (code, name, description, display_order, enabled)
VALUES ('PRO', 'Processing', 'Order being prepared', 3, 1);
INSERT INTO ALEDIESME.order_status (code, name, description, display_order, enabled)
VALUES ('ENVO', 'Shipped', 'Order shipped to the customer', 4, 1);
INSERT INTO ALEDIESME.order_status (code, name, description, display_order, enabled)
VALUES ('ENT', 'Delivered', 'Order delivered to the customer', 5, 1);
INSERT INTO ALEDIESME.order_status (code, name, description, display_order, enabled)
VALUES ('CAN', 'Cancelled', 'Order cancelled', 6, 1);
INSERT INTO ALEDIESME.order_status (code, name, description, display_order, enabled)
VALUES ('DEV', 'Returned', 'Order returned by the customer', 7, 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR payment_method
-- =====================================================
INSERT INTO ALEDIESME.payment_method (code, name, description, requires_validation, enabled)
VALUES ('TC', 'Credit Card', 'Payment with credit card', 1, 1);
INSERT INTO ALEDIESME.payment_method (code, name, description, requires_validation, enabled)
VALUES ('TD', 'Debit Card', 'Payment with debit card', 1, 1);
INSERT INTO ALEDIESME.payment_method (code, name, description, requires_validation, enabled)
VALUES ('TR', 'Bank Transfer', 'Payment by bank transfer', 1, 1);
INSERT INTO ALEDIESME.payment_method (code, name, description, requires_validation, enabled)
VALUES ('CE', 'Cash on Delivery', 'Payment upon product delivery', 0, 1);
INSERT INTO ALEDIESME.payment_method (code, name, description, requires_validation, enabled)
VALUES ('BD', 'Digital Wallet', 'Payment with digital wallet', 1, 1);

-- =====================================================
-- INSERT DEFAULT VALUES FOR customer (sample jewelry client)
-- =====================================================
INSERT INTO ALEDIESME.customer (
    user_type_id,
    document_type_id,
    document_number,
    first_name,
    last_name,
    email,
    phone,
    mobile_phone,
    gender_id,
    marital_status_id,
    birth_date,
    anniversary_date,
    neighborhood_id,
    address_line,
    address_complement,
    postal_code,
    preferred_currency_id,
    accepts_marketing,
    notes,
    enabled
)
SELECT
    ut.id,
    dt.id,
    '1234567890',
    'Maria',
    'Gomez',
    'maria.gomez@example.com',
    '6041234567',
    '3001234567',
    g.id,
    ms.id,
    DATE '1990-05-15',
    DATE '2015-06-20',
    n.id,
    'Calle 10 # 20-30',
    'Apto 501',
    '050001',
    c.id,
    1,
    'Prefiere oro amarillo 18K. Talla anillo 7.',
    1
FROM ALEDIESME.user_type ut
JOIN ALEDIESME.document_type dt ON dt.code = 'CC'
JOIN ALEDIESME.gender g ON g.code = 'F'
JOIN ALEDIESME.marital_status ms ON ms.code = 'C'
JOIN ALEDIESME.neighborhood n ON n.code = '05001001'
JOIN ALEDIESME.currency c ON c.code = 'COP'
WHERE ut.code = 'CLI';

-- ================================================================================
-- Indexes
-- ================================================================================
CREATE INDEX idx_state_province_country ON ALEDIESME.state_province (country_id);
CREATE INDEX idx_city_state_province ON ALEDIESME.city (state_province_id);
CREATE INDEX idx_neighborhood_city ON ALEDIESME.neighborhood (city_id);
CREATE INDEX idx_customer_user_type ON ALEDIESME.customer (user_type_id);
CREATE INDEX idx_customer_document_type ON ALEDIESME.customer (document_type_id);
CREATE INDEX idx_customer_neighborhood ON ALEDIESME.customer (neighborhood_id);
CREATE INDEX idx_customer_name ON ALEDIESME.customer (last_name, first_name);
CREATE INDEX idx_customer_mobile_phone ON ALEDIESME.customer (mobile_phone);

-- ===============================================================================================
-- Table comments
-- ===============================================================================================
COMMENT ON TABLE ALEDIESME.document_type IS 'Identification document types (CC, CE, PA, etc.)';
COMMENT ON TABLE ALEDIESME.country IS 'Master country catalog';
COMMENT ON TABLE ALEDIESME.state_province IS 'States, departments or provinces by country';
COMMENT ON TABLE ALEDIESME.city IS 'Cities or municipalities by state/province';
COMMENT ON TABLE ALEDIESME.neighborhood IS 'Neighborhoods or districts by city';
COMMENT ON TABLE ALEDIESME.gender IS 'Gender catalog (Male, Female, Other)';
COMMENT ON TABLE ALEDIESME.marital_status IS 'Marital status catalog (Single, Married, etc.)';
COMMENT ON TABLE ALEDIESME.user_type IS 'Application user types';
COMMENT ON TABLE ALEDIESME.currency IS 'Supported currencies';
COMMENT ON TABLE ALEDIESME.order_status IS 'Possible order statuses';
COMMENT ON TABLE ALEDIESME.payment_method IS 'Available payment methods';
COMMENT ON TABLE ALEDIESME.customer IS 'Jewelry store customers (business profile; login credentials live in app_user)';
COMMENT ON COLUMN ALEDIESME.customer.app_user_id IS 'Optional link to app_user when the customer has a web account. FK added in app_security_users.sql';
COMMENT ON COLUMN ALEDIESME.customer.user_type_id IS 'Business classification; use CLI (Client) from user_type catalog';
COMMENT ON COLUMN ALEDIESME.customer.anniversary_date IS 'Wedding or relationship anniversary for marketing and gift reminders';
COMMENT ON COLUMN ALEDIESME.customer.birth_date IS 'Birth date for birthday promotions';
COMMENT ON COLUMN ALEDIESME.customer.notes IS 'Sales preferences: metal type, ring size, style, etc.';
COMMENT ON COLUMN ALEDIESME.customer.accepts_marketing IS '1 = accepts promotional communications, 0 = opted out';

COMMIT;
