CREATE TABLE app_role (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
    enabled   INT         NOT NULL DEFAULT 1
);

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    enabled       INT          NOT NULL DEFAULT 1
);

CREATE TABLE app_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE user_type (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(10)  NOT NULL,
    name    VARCHAR(100) NOT NULL,
    enabled INT          NOT NULL DEFAULT 1
);

CREATE TABLE document_type (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(10)  NOT NULL,
    name    VARCHAR(100) NOT NULL,
    enabled INT          NOT NULL DEFAULT 1
);

CREATE TABLE customer (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id           BIGINT,
    user_type_id          BIGINT       NOT NULL,
    document_type_id      BIGINT       NOT NULL,
    document_number       VARCHAR(30)  NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(150),
    phone                 VARCHAR(30),
    mobile_phone          VARCHAR(30),
    gender_id             BIGINT,
    marital_status_id     BIGINT,
    birth_date            DATE,
    anniversary_date      DATE,
    neighborhood_id       BIGINT,
    address_line          VARCHAR(200),
    address_complement    VARCHAR(100),
    postal_code           VARCHAR(20),
    preferred_currency_id BIGINT,
    accepts_marketing     INT          NOT NULL DEFAULT 0,
    notes                 VARCHAR(500),
    enabled               INT          NOT NULL DEFAULT 1,
    created_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_customer_document UNIQUE (document_type_id, document_number),
    CONSTRAINT uk_customer_email UNIQUE (email)
);
