CREATE TABLE user_type (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(10)  NOT NULL,
    name    VARCHAR(100) NOT NULL,
    enabled INT          NOT NULL DEFAULT 1
);

CREATE TABLE document_type (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(10)  NOT NULL,
    name    VARCHAR(100) NOT NULL,
    enabled INT          NOT NULL DEFAULT 1
);

CREATE TABLE customer (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id           BIGINT,
    user_type_id          BIGINT       NOT NULL,
    document_type_id      BIGINT       NOT NULL,
    document_number       VARCHAR(30)  NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(150),
    phone                 VARCHAR(30),
    mobile_phone          VARCHAR(30),
    gender_id             BIGINT,
    marital_status_id     BIGINT,
    birth_date            DATE,
    anniversary_date      DATE,
    neighborhood_id       BIGINT,
    address_line          VARCHAR(200),
    address_complement    VARCHAR(100),
    postal_code           VARCHAR(20),
    preferred_currency_id BIGINT,
    accepts_marketing     INT          NOT NULL DEFAULT 0,
    notes                 VARCHAR(500),
    enabled               INT          NOT NULL DEFAULT 1,
    CONSTRAINT uk_customer_document UNIQUE (document_type_id, document_number),
    CONSTRAINT uk_customer_email UNIQUE (email)
);

INSERT INTO user_type (code, name, enabled) VALUES ('CLI', 'Client', 1);
INSERT INTO document_type (code, name, enabled) VALUES ('CC', 'Citizenship ID', 1);
